int Card.GetCode(card pcard)
int Card.GetOriginCode(card pcard)
int Card.GetOriginCodeRule(card pcard)
int Card.GetFusionCode(card pcard)
int Card.GetLinkCode(card pcard)
bool Card.IsFusionCode(card pcard, int|nil tcode)
bool Card.IsLinkCode(card pcard, int|nil tcode)
bool Card.IsSetCard(card pcard, int|nil set_code)
bool Card.IsOriginSetCard(card pcard, int|nil set_code)
bool Card.IsPreSetCard(card pcard, int|nil set_code)
bool Card.IsFusionSetCard(card pcard, int|nil set_code)
bool Card.IsLinkSetCard(card pcard, int|nil set_code)
bool Card.IsSpecialSummonSetCard(card pcard, int|nil set_code)
int Card.GetType(card pcard)
int Card.GetOriginType(card pcard)
int Card.GetFusionType(card pcard)
int Card.GetSynchroType(card pcard)
int Card.GetXyzType(card pcard)
int Card.GetLinkType(card pcard)
int Card.GetLevel(card pcard)
int Card.GetRank(card pcard)
int Card.GetLink(card pcard)
int Card.GetSynchroLevel(card pcard, card scard)
int Card.GetRitualLevel(card pcard, card scard)
int Card.GetOriginLevel(card pcard)
int Card.GetOriginRank(card pcard)
bool Card.IsXyzLevel(card pcard, card xyzcard, int lv)
int Card.GetLscale(card pcard)
int Card.GetOriginLscale(card pcard)
int Card.GetRscale(card pcard)
int Card.GetOriginRscale(card pcard)
int Card.GetCurrentScale(card pcard)
bool Card.IsLinkMarker(card pcard, int dir)
card Card.GetLinkedGroup(card pcard)
int Card.GetLinkedGroupCount(card pcard)
int Card.GetLinkedZone(card pcard/*, int|nil cp*/)
card Card.GetMutualLinkedGroup(card pcard)
int Card.GetMutualLinkedGroupCount(card pcard)
int Card.GetMutualLinkedZone(card pcard/*, int|nil cp*/)
bool Card.IsLinkState(card pcard)
bool Card.IsExtraLinkState(card pcard)
card Card.GetColumnGroup(card pcard)
int Card.GetColumnGroupCount(card pcard)
int Card.GetColumnZone(card pcard, int loc/*, int|nil cp*/)
bool Card.IsAllColumn(card pcard)
int Card.GetAttribute(card pcard)
int Card.GetOriginAttribute(card pcard)
int Card.GetFusionAttribute(card pcard/*, int|nil playerid*/)
int Card.GetLinkAttribute(card pcard/*, int|nil playerid*/)
int Card.GetAttributeInGrave(card pcard/*, int|nil playerid*/)
int Card.GetRace(card pcard)
int Card.GetOriginRace(card pcard)
int Card.GetLinkRace(card pcard/*, int|nil playerid*/)
int Card.GetRaceInGrave(card pcard/*, int|nil playerid*/)
int Card.GetAttack(card pcard)
int Card.GetOriginAttack(card pcard)
int Card.GetTextAttack(card pcard)
int Card.GetDefense(card pcard)
int Card.GetOriginDefense(card pcard)
int Card.GetTextDefense(card pcard)
int Card.GetPreviousCodeOnfield(card pcard)
int Card.GetPreviousTypeOnfield(card pcard)
int Card.GetPreviousLevelOnfield(card pcard)
int Card.GetPreviousRankOnfield(card pcard)
int Card.GetPreviousAttributeOnfield(card pcard)
int Card.GetPreviousRaceOnfield(card pcard)
int Card.GetPreviousAttackOnfield(card pcard)
int Card.GetPreviousDefenseOnfield(card pcard)
int Card.GetPreviousOverlayCountOnfield(card pcard)
int Card.GetOwner(card pcard)
int Card.GetControler(card pcard)
int Card.GetPreviousControler(card pcard)
nil Card.SetReason(card pcard, int reason)
int Card.GetReason(card pcard)
group Card.GetReasonCard(card pcard)
int Card.GetReasonPlayer(card pcard)
effect Card.GetReasonEffect(card pcard)
int Card.GetPosition(card pcard)
int Card.GetPreviousPosition(card pcard)
int Card.GetBattlePosition(card pcard)
int Card.GetLocation(card pcard)
int Card.GetPreviousLocation(card pcard)
int Card.GetSequence(card pcard)
int Card.GetPreviousSequence(card pcard)
int Card.GetSummonType(card pcard)
int Card.GetSummonLocation(card pcard)
int Card.GetSummonPlayer(card pcard)
effect|int Card.GetSpecialSummonInfo(card pcard/*, int flag*/)
int Card.GetDestination(card pcard)
int Card.GetLeaveFieldDest(card pcard)
int Card.GetTurnid(card pcard)
int Card.GetFieldid(card pcard)
int Card.GetFieldidr(card pcard)
bool Card.IsOriginCodeRule(card pcard, int|nil tcode)
bool Card.IsCode(card pcard, int|nil tcode)
bool Card.IsType(card pcard, int ttype)
bool Card.IsAllTypes(card pcard, int ttype)
bool Card.IsFusionType(card pcard, int ttype)
bool Card.IsSynchroType(card pcard, int ttype)
bool Card.IsXyzType(card pcard, int ttype)
bool Card.IsLinkType(card pcard, int ttype)
bool Card.IsLevel(card pcard, int|nil tlevel)
bool Card.IsRank(card pcard, int|nil trank)
bool Card.IsLink(card pcard, int|nil tlink)
bool Card.IsAttack(card pcard, int|nil tatk)
bool Card.IsDefense(card pcard, int|nil tdef)
bool Card.IsRace(card pcard, int trace)
bool Card.IsLinkRace(card pcard, int trace/*, int|nil playerid*/)
bool Card.IsAttribute(card pcard, int tattrib)
bool Card.IsFusionAttribute(card pcard, int tattrib/*, int|nil playerid*/)
bool Card.IsLinkAttribute(card pcard, int tattrib/*, int|nil playerid*/)
bool Card.IsNonAttribute(card pcard, int tattrib)
bool Card.IsExtraDeckMonster(card pcard)
bool Card.IsReason(card pcard, int treason)
bool Card.IsAllReasons(card pcard, int treason)
bool Card.IsSummonType(card pcard, int ttype)
bool Card.IsSummonLocation(card pcard, int tloc)
bool Card.IsSummonPlayer(card pcard, int con)
bool Card.IsStatus(card pcard, int tstatus)
bool Card.IsNotTuner(card pcard, card scard)
bool Card.IsTuner(card pcard, card scard)
bool Card.IsOriginalEffectProperty(card pcard, fn filter)
bool Card.IsEffectProperty(card pcard, fn filter)
nil Card.SetStatus(card pcard, int tstatus, bool enable)
bool Card.IsDualState(card pcard)
nil Card.EnableDualState(card pcard)
nil Card.SetTurnCounter(card pcard, int ct)
int Card.GetTurnCounter(card pcard)
nil Card.SetMaterial(card pcard, group|nil pgroup)
card Card.GetMaterial(card pcard)
int Card.GetMaterialCount(card pcard)
card Card.GetEquipGroup(card pcard)
int Card.GetEquipCount(card pcard)
group Card.GetEquipTarget(card pcard)
group Card.GetPreEquipTarget(card pcard)
bool Card.CheckEquipTarget(card pcard/*, card target*/)
bool Card.CheckUnionTarget(card pcard/*, card target*/)
int Card.GetUnionCount(card pcard)
card Card.GetOverlayGroup(card pcard)
int Card.GetOverlayCount(card pcard)
group Card.GetOverlayTarget(card pcard)
bool Card.CheckRemoveOverlayCard(card pcard, int playerid, int count, int reason)
int Card.RemoveOverlayCard(card pcard, int playerid, int min, int max, int reason)
card Card.GetAttackedGroup(card pcard)
int Card.GetAttackedGroupCount(card pcard)
int Card.GetAttackedCount(card pcard)
card Card.GetBattledGroup(card pcard)
int Card.GetBattledGroupCount(card pcard)
int Card.GetAttackAnnouncedCount(card pcard)
bool Card.IsDirectAttacked(card pcard)
nil Card.SetCardTarget(card pcard, card ocard)
card Card.GetCardTarget(card pcard)
group Card.GetFirstCardTarget(card pcard)
int Card.GetCardTargetCount(card pcard)
bool Card.IsHasCardTarget(card pcard, card rcard)
nil Card.CancelCardTarget(card pcard, card rcard)
card Card.GetOwnerTarget(card pcard)
int Card.GetOwnerTargetCount(card pcard)
effect Card.GetActivateEffect(card pcard)
card|effect|int Card.CheckActivateEffect(card pcard, bool neglect_con, bool neglect_cost, bool copy_info)
effect|fn|int Card.GetTunerLimit(card pcard)
effect|fn|int Card.GetHandSynchro(card pcard)
int Card.RegisterEffect(card pcard, effect peffect/*, bool forced*/)
effect Card.IsHasEffect(card pcard, int code/*, int check_player*/)
nil Card.ResetEffect(card pcard, int code, int type)
int Card.GetEffectCount(card pcard, int code)
effect Card.RegisterFlagEffect(card pcard, int code, int reset, int flag, int count/*, int lab, int desc*/)
int Card.GetFlagEffect(card pcard, int code)
nil Card.ResetFlagEffect(card pcard, int code)
bool Card.SetFlagEffectLabel(card pcard, int code, int lab)
int Card.GetFlagEffectLabel(card pcard, int code)
nil Card.CreateRelation(card pcard, card rcard, int reset)
nil Card.ReleaseRelation(card pcard, card rcard)
nil Card.CreateEffectRelation(card pcard, effect peffect)
nil Card.ReleaseEffectRelation(card pcard, effect peffect)
nil Card.ClearEffectRelation(card pcard)
bool Card.IsRelateToEffect(card pcard, effect peffect)
bool Card.IsRelateToChain(card pcard/*, int chain_count*/)
bool Card.IsRelateToCard(card pcard, card rcard)
bool Card.IsRelateToBattle(card pcard)
int Card.CopyEffect(card pcard, int code, int reset/*, int count*/)
int Card.ReplaceEffect(card pcard, int code, int reset/*, int count*/)
nil Card.EnableReviveLimit(card pcard)
nil Card.CompleteProcedure(card pcard)
bool Card.IsDisabled(card pcard)
bool Card.IsDestructable(card pcard/*, effect peffect*/)
bool Card.IsSummonable(card pcard)
bool Card.IsSpecialSummonableCard(card pcard)
bool Card.IsFusionSummonableCard(card pcard/*, int summon_type*/)
bool Card.IsMsetable(card pcard, bool ign, effect|nil peffect/*, int minc, int zone*/)
bool Card.IsSsetable(card pcard/*, bool ign*/)
bool Card.IsSpecialSummonable(card pcard/*, int sumtype*/)
bool Card.IsSynchroSummonable(card pcard, card|nil tuner/*, group|nil mg, int minc, int maxc*/)
bool Card.IsXyzSummonable(card pcard, group|nil materials/*, int minc, int maxc*/)
bool Card.IsLinkSummonable(card pcard, group|nil materials/*, card|nil lcard, int minc, int maxc*/)
bool Card.IsCanBeSummoned(card pcard, bool ign, effect|nil peffect/*, int minc, int zone*/)
bool Card.IsCanBeSpecialSummoned(card pcard, effect peffect, int sumtype, int sumplayer, bool nocheck, bool nolimit/*, int sumpos, int toplayer, int zone*/)
bool Card.IsCanBePlacedOnField(card pcard/*, int toplayer, int tolocation*/)
bool Card.IsAbleToHand(card pcard/*, int p*/)
bool Card.IsAbleToGrave(card pcard)
bool Card.IsAbleToDeck(card pcard)
bool Card.IsAbleToExtra(card pcard)
bool Card.IsAbleToRemove(card pcard/*, int p, int pos, int reason*/)
bool Card.IsAbleToHandAsCost(card pcard)
bool Card.IsAbleToGraveAsCost(card pcard)
bool Card.IsAbleToDeckAsCost(card pcard)
bool Card.IsAbleToExtraAsCost(card pcard)
bool Card.IsAbleToDeckOrExtraAsCost(card pcard)
bool Card.IsAbleToRemoveAsCost(card pcard/*, int pos*/)
bool Card.IsReleasable(card pcard/*, int reason*/)
bool Card.IsReleasableByEffect(card pcard)
bool Card.IsDiscardable(card pcard/*, int reason*/)
bool Card.IsAttackable(card pcard)
bool Card.IsChainAttackable(card pcard/*, int ac, bool monsteronly*/)
bool Card.IsFaceup(card pcard)
bool Card.IsFaceupEx(card pcard)
bool Card.IsAttackPos(card pcard)
bool Card.IsFacedown(card pcard)
bool Card.IsDefensePos(card pcard)
bool Card.IsPosition(card pcard, int pos)
bool Card.IsPrePosition(card pcard, int pos)
bool Card.IsControler(card pcard, int con)
bool Card.IsPreControler(card pcard, int con)
bool Card.IsOnfield(card pcard)
bool Card.IsLocation(card pcard, int loc)
bool Card.IsPreLocation(card pcard, int loc)
bool Card.IsLevelBelow(card pcard, int lvl)
bool Card.IsLevelAbove(card pcard, int lvl)
bool Card.IsRankBelow(card pcard, int rnk)
bool Card.IsRankAbove(card pcard, int rnk)
bool Card.IsLinkBelow(card pcard, int lnk)
bool Card.IsLinkAbove(card pcard, int lnk)
bool Card.IsAttackBelow(card pcard, int atk)
bool Card.IsAttackAbove(card pcard, int atk)
bool Card.IsDefenseBelow(card pcard, int def)
bool Card.IsDefenseAbove(card pcard, int def)
bool Card.IsHasLevel(card pcard)
bool Card.IsHasDefense(card pcard)
bool Card.IsPublic(card pcard)
bool Card.IsForbidden(card pcard)
bool Card.IsAbleToChangeControler(card pcard)
bool Card.IsControlerCanBeChanged(card pcard/*, bool ign, int zone*/)
bool Card.AddCounter(card pcard, int countertype, int count/*, bool singly*/)
bool Card.RemoveCounter(card pcard, int rplayer, int countertype, int count, int reason)
int Card.GetCounter(card pcard, int countertype)
nil Card.EnableCounterPermit(card pcard, int countertype/*, int prange, fn condition*/)
nil Card.SetCounterLimit(card pcard, int countertype, int limit)
bool Card.IsCanChangePosition(card pcard)
bool Card.IsCanTurnSet(card pcard)
bool Card.IsCanAddCounter(card pcard, int countertype, int count/*, bool singly, int loc*/)
bool Card.IsCanRemoveCounter(card pcard, int playerid, int countertype, int count, int reason)
bool Card.IsCanHaveCounter(card pcard, int countertype)
bool Card.IsCanOverlay(card pcard/*, int|nil playerid*/)
bool Card.IsCanBeFusionMaterial(card pcard/*, card|nil fcard, int summon_type*/)
bool Card.IsCanBeSynchroMaterial(card pcard/*, card scard, card tuner*/)
bool Card.IsCanBeRitualMaterial(card pcard, card|nil scard)
bool Card.IsCanBeXyzMaterial(card pcard, card|nil scard)
bool Card.IsCanBeLinkMaterial(card pcard, card|nil scard)
bool Card.CheckFusionMaterial(card pcard/*, group|nil pgroup, card|nil cg, int chkf, bool not_material*/)
bool Card.CheckFusionSubstitute(card pcard, card fcard)
bool Card.IsImmuneToEffect(card pcard, effect peffect)
bool Card.IsCanBeDisabledByEffect(card pcard, effect peffect/*, bool is_monster_effect*/)
bool Card.IsCanBeEffectTarget(card pcard/*, effect peffect*/)
bool Card.IsCanBeBattleTarget(card pcard, card bcard)
nil Card.AddMonsterAttribute(card pcard, int type/*, int attribute, int race, int level, int atk, int def*/)
nil Card.CancelToGrave(card pcard/*, bool cancel*/)
int Card.GetTributeRequirement(card pcard)
group Card.GetBattleTarget(card pcard)
card|bool Card.GetAttackableTarget(card pcard)
nil Card.SetHint(card pcard, int type, int value)
nil Card.ReverseInDeck(card pcard)
nil Card.SetUniqueOnfield(card pcard, int unique_pos, int unique_pos, fn|int unique_code/*, int location*/)
bool Card.CheckUniqueOnfield(card pcard, int check_player/*, int check_location, card icard*/)
nil Card.ResetNegateEffect(card pcard/*, int o*/)
nil Card.AssumeProp(card pcard, int assume_type, int assume_value)
str|val Card.SetSpsummonOnce(card pcard, int spsummon_code)
card Group.New()
card Group.Clone(group pgroup)
card Group.FromCards(/*, card|nil pcard*/)
nil Group.Delete(group pgroup)
nil Group.KeepAlive(group pgroup)
nil Group.Clear(group pgroup)
nil Group.AddCard(group pgroup, card pcard)
nil Group.RemoveCard(group pgroup, card pcard)
group Group.GetNext(group pgroup)
group Group.GetFirst(group pgroup)
int Group.GetCount(group pgroup)
card Group.Filter(group pgroup, fn o, card|group pexgroup)
int Group.FilterCount(group pgroup, fn o, card|group pexgroup)
card Group.FilterSelect(group pgroup, int playerid, fn o, int min, int max, card|group pexgroup)
card Group.Select(group pgroup, int playerid, int min, int max, card|group pexgroup)
group Group.SelectUnselect(group select_group, group unselect_group, int playerid/*, bool finishable, bool cancelable, int min, int max*/)
card Group.RandomSelect(group pgroup, int playerid, int count)
card Group.CancelableSelect(group pgroup, int playerid, int min, int max, card|group pexgroup)
bool Group.IsExists(group pgroup, fn o, int count, card|group pexgroup)
bool Group.CheckWithSumEqual(group pgroup, fn o, int acc, int min, int max)
card Group.SelectWithSumEqual(group pgroup, int playerid, fn o, int acc, int min, int max)
bool Group.CheckWithSumGreater(group pgroup, fn o, int acc)
card Group.SelectWithSumGreater(group pgroup, int playerid, fn o, int acc)
card|int Group.GetMinGroup(group pgroup, fn o)
card|int Group.GetMaxGroup(group pgroup, fn o)
int Group.GetSum(group pgroup, fn o)
int Group.GetClassCount(group pgroup, fn o)
nil Group.Remove(group pgroup, fn o, card|nil pexception)
nil Group.Merge(group pgroup, group mgroup)
nil Group.Sub(group pgroup, group sgroup)
bool Group.Equal(group pgroup, group sgroup)
bool Group.IsContains(group pgroup, card pcard)
group Group.SearchCard(group pgroup, fn o)
int Group.GetBinClassCount(group pgroup, fn o)
card Group.MetaAdd(card|group cgroup, card|group cgroup)
card Group.MetaSub(card|group cgroup, card|group cgroup)
card Group.MetaBand(card|group cgroup, card|group cgroup)
card|str|val Group.MetaBxor(card|group cgroup, card|group cgroup)
effect Effect.New(card pcard)
effect Effect.Newex()
effect Effect.Clone(effect peffect)
nil Effect.Reset(effect peffect)
nil Effect.GetFieldId()
nil Effect.SetDescription(effect peffect, int v)
nil Effect.SetCode(effect peffect, int v)
nil Effect.SetRange(effect peffect, int v)
nil Effect.SetTargetRange(effect peffect, int s, int o)
nil Effect.SetAbsoluteRange(effect peffect, int playerid, int s, int o)
nil Effect.SetCountLimit(effect peffect, int v/*, int code*/)
nil Effect.SetReset(effect peffect, int v/*, int c*/)
nil Effect.SetType(effect peffect, int v)
nil Effect.SetProperty(effect peffect, int v1/*, int v2*/)
nil Effect.SetLabel(effect peffect, int o)
nil Effect.SetLabelObject(effect peffect, card|group|effect|nil p)
nil Effect.SetCategory(effect peffect, int v)
nil Effect.SetHintTiming(effect peffect, int vs/*, int vo*/)
nil Effect.SetCondition(effect peffect, fn condition)
nil Effect.SetTarget(effect peffect, fn target)
nil Effect.SetCost(effect peffect, fn cost)
nil Effect.SetValue(effect peffect, bool|fn|int value)
nil Effect.SetOperation(effect peffect, fn|nil operation)
nil Effect.SetOwnerPlayer(effect peffect/*, int p*/)
nil Effect.GetDescription()
nil Effect.GetCode()
nil Effect.GetType()
int Effect.GetProperty(effect peffect)
int Effect.GetLabel(effect peffect)
nil Effect.GetLabelObject(effect|obj peffect)
nil Effect.GetCategory()
nil Effect.GetRange()
group Effect.GetOwner(effect peffect)
group Effect.GetHandler(effect peffect)
int Effect.GetOwnerPlayer(effect peffect)
int Effect.GetHandlerPlayer(effect peffect)
fn Effect.GetCondition(effect peffect)
fn Effect.GetTarget(effect peffect)
fn Effect.GetCost(effect peffect)
fn|int Effect.GetValue(effect peffect)
fn Effect.GetOperation(effect peffect)
int Effect.GetActiveType(effect peffect)
bool Effect.IsActiveType(effect peffect, int type)
bool Effect.IsHasProperty(effect peffect, int tflag1/*, int tflag2*/)
nil Effect.IsHasCategory()
nil Effect.IsHasType()
nil Effect.IsHasRange()
bool Effect.IsActivatable(effect peffect, int playerid/*, bool neglect_loc, bool neglect_target*/)
bool Effect.IsActivated(effect peffect)
bool Effect.IsCostChecked(effect peffect)
nil Effect.SetCostCheck(effect peffect, bool cost_check)
int Effect.GetActivateLocation(effect peffect)
int Effect.GetActivateSequence(effect peffect)
bool Effect.CheckCountLimit(effect peffect, int p)
str|val Effect.UseCountLimit(effect peffect, int p/*, int count, bool oath_only*/)
nil Duel.EnableGlobalFlag(int flag)
int Duel.GetLp(int p)
nil Duel.SetLp(int p, int lp)
bool Duel.IsTurnPlayer(int playerid)
int Duel.GetTurnPlayer()
int Duel.GetTurnCount(/*, int playerid*/)
int Duel.GetDrawCount(int playerid)
nil Duel.RegisterEffect(effect peffect, int playerid)
effect Duel.RegisterFlagEffect(int playerid, int code, int reset, int flag, int count/*, int lab*/)
int Duel.GetFlagEffect(int playerid, int code)
nil Duel.ResetFlagEffect(int playerid, int code)
bool Duel.SetFlagEffectLabel(int playerid, int code, int lab)
int Duel.GetFlagEffectLabel(int playerid, int code)
int Duel.Destroy(card|group pgroup, int reason/*, int dest, int reason_player*/)
int Duel.Remove(card|group pgroup, int pos, int reason/*, int reason_player*/)
int Duel.SendtoGrave(card|group pgroup, int reason/*, int reason_player*/)
nil Duel.Summon(int playerid, card pcard, bool ignore_count, effect|nil peffect/*, int min_tribute, int zone*/)
nil Duel.SpecialSummonRule(int playerid, card pcard/*, int sumtype*/)
nil Duel.SynchroSummon(int playerid, card pcard, card|nil tuner/*, group|nil pgroup, int minc, int maxc*/)
nil Duel.XyzSummon(int playerid, card pcard, group|nil pgroup/*, int minc, int maxc*/)
nil Duel.LinkSummon(int playerid, card pcard, group|nil pgroup/*, card|nil lcard, int minc, int maxc*/)
nil Duel.Setm(int playerid, card pcard, bool ignore_count, effect|nil peffect/*, int min_tribute, int zone*/)
int Duel.Sets(int playerid, card|group pgroup/*, int toplayer, bool confirm*/)
group|bool Duel.CreateToken(int playerid, int code)
int Duel.SpecialSummon(card|group pgroup, int sumtype, int sumplayer, int playerid, bool nocheck, bool nolimit, int positions/*, int zone*/)
bool Duel.SpecialSummonStep(card pcard, int sumtype, int sumplayer, int playerid, bool nocheck, bool nolimit, int positions/*, int zone*/)
int Duel.SpecialSummonComplete()
int Duel.SendtoHand(card|group pgroup, int|nil playerid, int reason/*, int reason_player*/)
int Duel.SendtoDeck(card|group pgroup, int|nil playerid, int sequence, int reason/*, int reason_player, bool send_activating*/)
int Duel.SendtoExtra(card|group pgroup, int|nil playerid, int reason)
card Duel.GetOperatedGroup()
bool Duel.IsCanAddCounter(int playerid/*, int countertype, int count, card pcard*/)
bool Duel.RemoveCounter(int rplayer, int s, int o, int countertype, int count, int reason)
bool Duel.IsCanRemoveCounter(int rplayer, int s, int o, int countertype, int count, int reason)
int Duel.GetCounter(int playerid, int s, int o, int countertype)
int Duel.ChangeForm(card|group pgroup, int au/*, int ad, int du, int dd, bool o*/)
int Duel.Release(card|group pgroup, int reason/*, int reason_player*/)
bool Duel.MoveToField(card pcard, int move_player, int playerid, int destination, int positions, bool enable/*, int zone*/)
bool Duel.ReturnToField(card pcard/*, int pos, int zone*/)
nil Duel.MoveSequence(card pcard, int seq)
nil Duel.SwapSequence(card pcard1, card pcard2)
nil Duel.ActivateEffect(effect peffect)
nil Duel.SetChainLimit(fn f)
nil Duel.SetChainLimitP(fn f)
effect Duel.GetChainMaterial(int playerid)
nil Duel.ConfirmDecktop(int playerid, int count)
nil Duel.ConfirmExtratop(int playerid, int count)
nil Duel.ConfirmCards(int playerid, card|group pgroup/*, bool skip_panel*/)
nil Duel.SortDecktop(int sort_player, int target_player, int count)
card|effect|bool|int Duel.CheckEvent(int ev/*, bool get_info*/)
nil Duel.RaiseEvent(card|group pgroup, int code, effect|nil peffect, int r, int rp, int ep, int ev)
nil Duel.RaiseSingleEvent(card pcard, int code, effect|nil peffect, int r, int rp, int ep, int ev)
bool Duel.CheckTiming(int tm)
bool Duel.IsEnvironment(int code/*, int playerid, int loc*/)
nil Duel.Win(int playerid, int reason)
int Duel.Draw(int playerid, int count, int reason)
int Duel.Damage(int playerid, int amount, int reason/*, bool is_step*/)
int Duel.Recover(int playerid, int amount, int reason/*, bool is_step*/)
nil Duel.RdComplete()
bool Duel.Equip(int playerid, card equip_card, card target/*, bool up, bool step*/)
nil Duel.EquipComplete()
int Duel.GetControl(card|group pgroup, int playerid/*, int reset_phase, int reset_count, int zone*/)
bool Duel.SwapControl(card|group pgroup1, card|group pgroup2/*, int reset_phase, int reset_count*/)
bool Duel.CheckLpCost(int playerid, int cost/*, bool must_pay*/)
nil Duel.PayLpCost(int playerid, int cost/*, bool must_pay*/)
int Duel.DiscardDeck(int playerid, int count, int reason)
int Duel.DiscardHand(int playerid, fn|nil o, int min, int max, int reason/*, card|group pexgroup*/)
nil Duel.DisableShuffleCheck(/*, bool disable*/)
nil Duel.DisableSelfDestroyCheck(/*, bool disable*/)
nil Duel.RevealSelectDeckSequence(/*, bool reveal*/)
nil Duel.ShuffleDeck(int playerid)
nil Duel.ShuffleExtra(int playerid)
nil Duel.ShuffleHand(int playerid)
nil Duel.ShuffleSetcard(group pgroup)
nil Duel.ChangeAttacker(card attacker/*, bool ignore_count*/)
bool Duel.ChangeAttackTarget(card|nil target)
nil Duel.CalculateDamage(card attacker, card|nil attack_target/*, bool new_attack*/)
int Duel.GetBattleDamage(int playerid)
nil Duel.ChangeBattleDamage(int playerid, int dam/*, bool check*/)
nil Duel.ChangeTarget(int count, group pgroup)
nil Duel.ChangeTargetPlayer(int count, int playerid)
nil Duel.ChangeTargetParam(int count, int param)
nil Duel.BreakEffect()
nil Duel.ChangeEffect(int count, fn pf)
bool Duel.NegateActivate(int c)
bool Duel.NegateEffect(int c/*, bool forced*/)
nil Duel.NegateRelatedChain(card pcard, int reset_flag)
nil Duel.DisableSummon(card|group pgroup)
nil Duel.IncreaseSummonCount(/*, card pcard*/)
bool Duel.CheckSummonCount(/*, card pcard*/)
int Duel.GetLocationCount(int playerid, int location/*, int|nil uplayer, int reason, int zone*/)
int Duel.GetMzoneCount(int playerid/*, card|group|nil mgroup, int uplayer, int reason, int zone*/)
int Duel.GetSzoneCount(int playerid/*, card|group|nil mgroup, int uplayer, int reason, int zone*/)
int Duel.GetLocationCountFromex(int playerid/*, int|nil uplayer, card|group|nil mgroup, card|int|nil type, int zone*/)
int Duel.GetUsableMzoneCount(int playerid/*, int uplayer*/)
card Duel.GetLinkedGroup(int rplayer, int s, int o)
int Duel.GetLinkedGroupCount(int rplayer, int s, int o)
int Duel.GetLinkedZone(int playerid)
group Duel.GetFieldCard(int playerid, int location, int sequence)
bool Duel.CheckLocation(int playerid, int location, int sequence)
int Duel.GetCurrentChain()
int Duel.GetReadyChain()
card|effect|int Duel.GetChainInfo(int c/*, int flag*/)
card|effect|int Duel.GetChainEvent(int count)
group Duel.GetFirstTarget()
card Duel.GetTargetsRelateToChain()
bool Duel.IsPhase(int pphase)
bool Duel.IsMainPhase()
bool Duel.IsBattlePhase()
int Duel.GetCurrentPhase()
nil Duel.SkipPhase(int playerid, int phase, int reset, int count/*, int value*/)
bool Duel.IsDamageCalculated()
group Duel.GetAttacker()
group Duel.GetAttackTarget()
group Duel.GetBattleMonster(int playerid)
bool Duel.DisableAttack()
nil Duel.ChainAttack(/*, card chain_attack_target*/)
nil Duel.Readjust()
nil Duel.AdjustInstantly(/*, card pcard*/)
nil Duel.AdjustAll()
card Duel.GetFieldGroup(int playerid, int location1, int location2)
int Duel.GetFieldGroupCount(int playerid, int location1, int location2)
card Duel.GetDecktopGroup(int playerid, int count)
card Duel.GetExtratopGroup(int playerid, int count)
card Duel.GetMatchingGroup(fn|nil o, int self, int location1, int location2, card|group pexgroup)
int Duel.GetMatchingCount(fn|nil o, int self, int location1, int location2, card|group pexgroup)
group Duel.GetFirstMatchingCard(fn|nil o, int self, int location1, int location2, card|group pexgroup)
bool Duel.IsExistingMatchingCard(fn|nil o, int self, int location1, int location2, int fcount, card|group pexgroup)
card Duel.SelectMatchingCards(int playerid, fn|nil o, int self, int location1, int location2, int min, int max, card|group pexgroup)
card Duel.GetReleaseGroup(int playerid/*, bool hand, int reason*/)
int Duel.GetReleaseGroupCount(int playerid/*, bool hand, int reason*/)
bool Duel.CheckReleaseGroup(/*, int playerid, fn|nil o, int fcount, card|group pexgroup*/)
card Duel.SelectReleaseGroup(/*, int playerid, fn|nil o, int min, int max, card|group pexgroup*/)
bool Duel.CheckReleaseGroupEx(/*, int playerid, fn|nil o, int fcount, int reason, bool use_hand, card|group pexgroup*/)
card Duel.SelectReleaseGroupEx(/*, int playerid, fn|nil o, int min, int max, int reason, bool use_hand, card|group pexgroup*/)
card Duel.GetTributeGroup(card target)
int Duel.GetTributeCount(card target/*, group|nil mg, bool ex*/)
bool Duel.CheckTribute(card target, int min/*, int|nil max, group|nil mg, int|nil toplayer, int|nil zone*/)
card Duel.SelectTribute(int playerid, card target, int min, int max/*, group|nil mg, int toplayer*/)
int Duel.GetTargetCount(fn|nil o, int self, int location1, int location2, card|group pexgroup)
bool Duel.IsExistingTarget(fn|nil o, int self, int location1, int location2, int count, card|group pexgroup)
card Duel.SelectTarget(int playerid, fn|nil o, int self, int location1, int location2, int min, int max, card|group pexgroup)
card Duel.GetMustMaterial(int playerid, int limit)
bool Duel.CheckMustMaterial(int playerid, card|group mgroup, int limit)
card Duel.SelectFusionMaterial(int playerid, card pcard, group pgroup/*, card|nil cg, int chkf, bool not_material*/)
nil Duel.SetFusionMaterial(group pgroup)
nil Duel.SetSynchroMaterial(group pgroup)
card Duel.GetSynchroMaterial(int playerid/*, bool facedown*/)
nil Duel.SelectSynchroMaterial(int playerid, card pcard, fn|nil filter1, fn|nil filter2, int min, int max/*, card|nil smat, group|nil mg*/)
bool Duel.CheckSynchroMaterial(card pcard, fn|nil o, fn|nil o, int min, int max/*, card|nil smat, group|nil mg*/)
nil Duel.SelectTunerMaterial(int playerid, card pcard, card tuner, fn|nil filter1, fn|nil filter2, int min, int max/*, group|nil mg*/)
bool Duel.CheckTunerMaterial(card pcard, card tuner, fn|nil o, fn|nil o, int min, int max/*, group|nil mg*/)
card Duel.GetRitualMaterial(int playerid)
card Duel.GetRitualMaterialEx(int playerid)
nil Duel.ReleaseRitualMaterial(group pgroup)
card Duel.GetFusionMaterial(int playerid/*, int location*/)
bool Duel.IsSummonCancelable()
nil Duel.SetMustSelectCards(card|group pgroup)
card Duel.GrabMustSelectCards()
nil Duel.SetTargetCard(card|group pgroup)
nil Duel.ClearTargetCard()
nil Duel.SetTargetPlayer(int playerid)
nil Duel.SetTargetParam(int param)
nil Duel.SetOperationInfo(int ct, int cate, card|group pgroup, int count, int playerid, int param)
card|bool|int Duel.GetOperationInfo(int ct, int cate)
int Duel.GetOperationCount(int ct)
nil Duel.ClearOperationInfo(int ct)
bool Duel.CheckXyzMaterial(card scard, fn|nil o, int lv, int minc, int maxc, group|nil mg)
nil Duel.SelectXyzMaterial(int playerid, card scard, fn|nil o, int lv, int minc, int maxc/*, group|nil mg*/)
nil Duel.Overlay(card target, card|group pgroup/*, bool adjust*/)
card Duel.GetOverlayGroup(int rplayer, int s, int o)
int Duel.GetOverlayCount(int rplayer, int s, int o)
bool Duel.CheckRemoveOverlayCard(int playerid, int s, int o, int count, int reason)
int Duel.RemoveOverlayCard(int playerid, int s, int o, int min, int max, int reason)
nil Duel.Hint(int htype, int playerid, int desc)
int Duel.GetLastSelectHint(/*, int playerid*/)
nil Duel.HintSelection(group pgroup)
bool Duel.SelectEffectYesno(int playerid, card pcard/*, int desc*/)
bool Duel.SelectYesno(int playerid, int desc)
int Duel.SelectOption(int playerid/*, int o*/)
nil Duel.SelectSequence()
int Duel.SelectPosition(int playerid, card pcard, int positions)
int Duel.SelectDisableField(int playerid, int count, int location1, int location2, int filter)
int Duel.SelectField(int playerid, int count, int location1, int location2, int filter/*, int code*/)
int Duel.AnnounceRace(int playerid, int count, int available)
int Duel.AnnounceAttribute(int playerid, int count, int available)
int Duel.AnnounceLevel(int|nil playerid/*, int|nil min, int|nil max*/)
int Duel.AnnounceCard(int playerid)
int Duel.AnnounceType(int playerid)
int Duel.AnnounceNumber(int playerid, int o)
int Duel.AnnounceCoin(int playerid)
int Duel.TossCoin(int playerid, int count)
int Duel.TossDice(int playerid, int count1/*, int count2*/)
int Duel.RockPaperScissors(/*, bool repeat*/)
int Duel.GetCoinResult()
int Duel.GetDiceResult()
nil Duel.SetCoinResult(/*, int res*/)
nil Duel.SetDiceResult(/*, int res*/)
effect Duel.IsPlayerAffectedByEffect(int playerid, int code)
bool Duel.IsPlayerCanDraw(int playerid/*, int count*/)
bool Duel.IsPlayerCanDiscardDeck(int playerid, int count)
bool Duel.IsPlayerCanDiscardDeckAsCost(int playerid, int count)
bool Duel.IsPlayerCanSummon(int playerid/*, int sumtype, card pcard*/)
bool Duel.IsPlayerCanMset(int playerid/*, int sumtype, card pcard*/)
bool Duel.IsPlayerCanSset(int playerid/*, card pcard*/)
bool Duel.IsPlayerCanSpsummon(int playerid/*, int sumtype, int sumpos, int toplayer, card pcard*/)
bool Duel.IsPlayerCanFlipsummon(int playerid/*, card pcard*/)
bool Duel.IsPlayerCanSpsummonMonster(int playerid, int code/*, int|nil o, int|nil type, int|nil attack, int|nil defense, int|nil level, int|nil race, int|nil attribute, int pos, int toplayer, int sumtype*/)
bool Duel.IsPlayerCanSpsummonCount(int playerid, int count)
bool Duel.IsPlayerCanRelease(int playerid/*, card pcard, int reason*/)
bool Duel.IsPlayerCanRemove(int playerid/*, card pcard, int reason*/)
bool Duel.IsPlayerCanSendToHand(int playerid/*, card pcard*/)
bool Duel.IsPlayerCanSendToGrave(int playerid/*, card pcard*/)
bool Duel.IsPlayerCanSendToDeck(int playerid/*, card pcard*/)
bool Duel.IsPlayerCanAdditionalSummon(int playerid)
bool Duel.IsChainSolving()
bool Duel.IsChainNegatable()
bool Duel.IsChainDisablable(int chaincount)
bool Duel.IsChainDisabled(int chaincount)
bool Duel.CheckChainTarget(int chaincount, card pcard)
bool Duel.CheckChainUniqueness()
int Duel.GetActivityCount(int playerid, int activity_type)
bool Duel.CheckPhaseActivity()
nil Duel.AddCustomActivityCounter(int counter_id, int activity_type, fn counter_filter)
int Duel.GetCustomActivityCount(int counter_id, int playerid, int activity_type)
int Duel.GetBattledCount(int playerid)
bool Duel.IsAbleToEnterBp()
nil Duel.SwapDeckAndGrave(int playerid)
nil Duel.MajesticCopy(card pcard, card copy_target)
val Debug.Message(str o)
group Debug.AddCard(int code, int owner, int playerid, int location, int sequence, int position/*, bool proc*/)
nil Debug.SetPlayerInfo(int playerid, int lp, int startcount, int drawcount)
nil Debug.PreSummon(card pcard, int summon_type/*, int summon_location*/)
bool Debug.PreEquip(card equip_card, card target)
nil Debug.PreSetTarget(card t_card, card target)
nil Debug.PreAddCounter(card pcard, int countertype/*, int count*/)
nil Debug.ReloadFieldBegin(int flag/*, int rule*/)
nil Debug.ReloadFieldEnd()
nil Debug.SetAiName(str pstr)
val Debug.ShowHint(str pstr)
